### ISSUE TITLE
am i doing something wrong

### ISSUE THREAD

**Issue by Jeisonx** [antosha417/supreme-bot#1]
is it supposed to look like this?
<img width="1377" alt="screen shot 2017-09-28 at 1 25 37 pm" src="https://user-images.githubusercontent.com/22186712/30980896-0daa066c-a42f-11e7-83d5-bb541bb956d0.png">

this happens when i click sign in
<img width="846" alt="screen shot 2017-09-28 at 1 25 45 pm" src="https://user-images.githubusercontent.com/22186712/30980911-1e5d61ac-a42f-11e7-8acf-f325e1d4bf8c.png">

**Comment by antosha417** [comment]
1.

**Comment by antosha417** [comment]
1. You should serve static files form [static dirrectory](https://github.com/antosha417/supreme-bot/tree/master/app/static) for site to look pretty. I did it using nginx.
2. If you want vk auth to work properly, you should [create vk app (Website) ](https://vk.com/editapp?act=create), insert your URL and change [settings](https://github.com/antosha417/supreme-bot/blob/master/app/config.py).

**Comment by antosha417** [comment]
P.S. I wote this before google captcha was used in supreme-shop. So I doubt that something will work now.
